import Head from "next/head";
import { Dashboard } from "@/modules/dashboard/page";

export default function Home() {
  return (
    <>
      <Head>
        <title>17Studio Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard />
    </>
  );
}
